/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import org.chocosolver.solver.Model
import org.chocosolver.solver.variables.IntVar
import kotlin.test.Test
import kotlin.test.assertEquals

internal class AppTest {
    @Test
    fun firstExampleTest() {
        val model = Model()

        // definition of the variables
        val numValues = 3
        val x: IntVar = model.intVar("x", 1, numValues)
        val y = model.intVar("y", 1, numValues)
        val z = model.intVar("z", 1, numValues)

        // definition of constraints
        model.arithm(x, "!=", y).post()

        // searching for a feasible solution
        val solver = model.solver
        solver.solve()

        assertEquals(x.value, 1)
        assertEquals(y.value, 2)
        assertEquals(z.value, 1)
    }
}
