/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4/userguide/multi_project_builds.html
 */

rootProject.name = "ChocoKt"
include("first_example")
include("second_example")
include("third_example")
include("fourth_example")
include("fifth_example")
include("sixth_example")
include("precision")
include("2p-kt-example")
include("clp-var-creation")
include("real_variables")
include("clpqr")
